-- Enriched-leads store for the /leads command center + the batch enricher output.
-- Run once in the Supabase SQL editor. The /leads page enriches live today; this
-- table is where batch runs (enricher/enrich.mjs) + persisted results will live.
CREATE TABLE IF NOT EXISTS enriched_leads (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host        text,
  company     text,
  contact     text,
  title       text,
  phone       text,
  email       text,
  city        text,
  state       text,
  website     text,
  vertical    text,
  score       integer,
  tier        text,
  runs_ads    boolean DEFAULT false,
  signals     jsonb   DEFAULT '{}'::jsonb,
  call_opener text,
  email_line  text,
  source_list text,
  status      text    DEFAULT 'new',   -- new | called | emailed | booked | skip
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS enriched_leads_host_idx  ON enriched_leads (host);
CREATE INDEX        IF NOT EXISTS enriched_leads_score_idx ON enriched_leads (score DESC);
