-- V-Rank: turn the shared tool_clients table into a multi-product account table,
-- and add the geo_metrics table that stores each customer's real AI-visibility data.
-- Run this once in Supabase (SQL editor) before launching V-Rank.

-- 1) Plan discriminator + V-Rank target site on the shared account table.
ALTER TABLE tool_clients ADD COLUMN IF NOT EXISTS plan text NOT NULL DEFAULT 'recaller';  -- 'recaller' | 'vrank'
ALTER TABLE tool_clients ADD COLUMN IF NOT EXISTS website text;

-- 2) Real V-Rank metrics per customer (else dashboards fall back to mock data).
CREATE TABLE IF NOT EXISTS geo_metrics (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id             text NOT NULL,
  score                 integer DEFAULT 0,
  traffic               integer DEFAULT 0,
  ai_referrals          integer DEFAULT 0,
  indexed_pages         integer DEFAULT 0,
  generated_this_month  integer DEFAULT 0,
  rankings              jsonb   DEFAULT '[]'::jsonb,
  citations             jsonb   DEFAULT '[]'::jsonb,
  created_at            timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS geo_metrics_client_idx ON geo_metrics (client_id, created_at DESC);
